# This is a basic workflow to help you get started with Actions

name: deploy-cf

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

on:
  push:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CloudFormation lint action
      uses: ryof/cloudformation-lint-action@1.0.1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Deploy Static Site
        id: deploy-cfn
        uses: alexjurkiewicz/cfn-deploy@v2.0.1
        with:
          stackName: lorem-static
          templateFile: static_site.yml
          noExecuteChangeset: true
          parameters: DomainName=kristianjlee.com LogsLifecycle=true CertificateARN=${{ secrets.certificate_arn }} DNSZoneID=${{ secrets.dnszone_id }}
      - name: Print App Hostname
        run: echo ${{ steps.deploy-cfn.outputs.cf_output_Website }}
